name: cron-tab

on: 
  schedule:
    -  cron: "* * * * *"
    
jobs:  
  startup:
    runs-on: ubuntu-latest

    steps:
      -  name: hi
         run: echo "thampi sundar inga vaa paa"
       
  
  
    
