name: start with gibhubactions
on:
  push:
    branches: 
      -  main
jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      -  name: checkout code
         uses: actions/checkout@v2

      -  name: install java
         run: actions/setup-java@v3
         with:
            java-version: '11'
            distribution: 'open-jdk'

      -  name: verify java
         run: java --version

      -  name: mvn install
         run: mvn install
